apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort  # Exposes the service on port 8080 of the Minikube node
  selector:
    app: hello-world-api-master
  ports:
    - protocol: TCP
      port: 3000  # The internal container port
      targetPort: 3000  # Same as the container port
      nodePort: 8080  # Expose the service on Minikube node's port 8080
