apiVersion: v1
kind: Service
metadata:
  name: hello-world-api-service
spec:
  type: NodePort
  selector:
    app: hello-world-api-master
  ports:
    - protocol: TCP
      port: 8080       # The port exposed by the service
      targetPort: 3000 # The port your pods are listening on
      nodePort: 8080   # The NodePort to expose externally